### ISSUE TITLE
non-hex keys

### ISSUE THREAD

**Issue by MareoRaft** [cluracan/send-tokens#3]
Would it be difficult to support keys that are not Hex-encoded 32-byte?  I imagine some users will have such keys, and we could potentially make it more convenient for them if we can support those keys.  In the meantime, I'll do a little research so I can understand the issue better.

**Comment by MareoRaft** [comment]
It seems in my case the key was already Hex-encoded 32-byte, and simply ommitted the "0x" characters at the beginning.  In that case, it could be helpful to the user to automatically prepend the "0x" under the condition that it's 64 characters long and only uses characters 0-9 a-f.  But this could be dangerous if there is a possibility that a key is *not* hex-encoded and just so happens to be in the right format to look like it is.  I don't know much about etherium private keys, so I don't know if this "dangerous" scenario would happen or not.

**Comment by MareoRaft** [comment]
So this leads to the question of whether we need to worry about non-32-byte keys.  Do etherium private keys that are, for example, 64 bytes instead of 32 bytes exist?

**Comment by cluracan** [comment]
Yeah, it's usually *not* a good idea to be too permissive in crypto as you really want the user to be very conscious of what they're doing.

If I may make a suggestion, and if you haven't done so already, you might consider displaying an "ethereum blockie" image for address fields as a visual check.

Private keys are always 32 bytes. Anything more or less shouldn't work.

**Comment by MareoRaft** [comment]
Okay, that makes sense.  Yes, I'll try to add in blockies.  I'll try out 

https://github.com/ethereum/blockies

unless you have one to recommend
