### ISSUE TITLE
can we change default unit to 1 token?

### ISSUE THREAD

**Issue by MareoRaft** [cluracan/send-tokens#4]
I would like to make a proposal for a "major" change, in the sense that it would require incrementing the major version number of the project.  I've thought a lot about this, so please hear me out :)

## default unit proposal

Given the contract (token) address, the default (user-facing) unit of currency in this repo is 10^(-18) tokens.  I propose changing it to 1 token.  (It is perfectly fine if a different unit is used internally)

## why?

While it is common (and you probably know better than I do) to use 10^(-18) tokens as the unit in smart contracts, I think it is common to use 1 token as the unit for user-facing wallets.  For example, if a user wants to send his friend some money in Bela, he usually thinks "I'm going to send John 15 Bela".  Since this repo is user-facing and not meant as a building block for smart contracts, I think it will be easier for users if an amount of "4" and all other options default would send 4 tokens.  The popular MEW which focuses on etherium and etherium tokens also follows the convention of using 1 token (when sending ERC20 tokens) or 1 ether (when working in etherium) as the default unit that amounts are expressed in.  Also, as a "token" is the unit that was chosen to express ERC20 currency amounts in the first place, changing that unit introduces an extra layer of complication.

## exponentiation naming scheme proposal

I propose changing the name of the "base" option to "exponent" and changing "b" to "e" and/or "E".

## why?

Consider a situation of exponentiation such as 10^7.  In mathematics, the word "base" refers to the number that it repeatedly multiplied by itself (in this case 10), while the word "power" or "exponent" refers to the number of times the base is multiplied by itself (in this case 7).  Since we are expressing amounts in the form 3 * 10^7 (for example), the most reasonable choice for variable names referring to the "7" are "power", "exponent", and "order" ("order" being a shortening of "order of magnitude").  I think "exponent" is most appropriate because there is already a prevailing convention and international standard of expressing a number in the form 3e7 or 3E7 (for example).  In that convention (https://en.wikipedia.org/wiki/Scientific_notation#E-notation), the "e" does in fact stand for "exponent".

## default exponent value proposal

I propose changing the default exponent to 0.

## why?

For the same reasons as in the default unit proposal, I believe a user entering "4" as the amount and accepting all defaults should sent 4 tokens.  Since 4 = 4e0, this would necessitate a default exponent of 0.

## 'migration' proposal

I propose warning Tyler and anybody who starred this repo directly about the upcoming change and making this change sooner rather than later.  I would also add a warning message in the send-tokens CLI itself to warn people about the change and force them to hit enter to continue the transaction.  This warning can be temporary for a few months.

## why?

My natural instinct is to worry that this change will cause people to accidentally send the wrong amount to others.  However, there are some good reasons why this should not be a huge issue.  Firstly, this repository is extremely young (only 1 month old).  There is a good chance that you only have 1 or 2 users at this point.  Better to bite the bullet now than later, when the repo becomes super popular!  Secondly, a factor of 10^18 is so large that it works in our favor.  Someone trying to send 1 Bela, for example, would now try to send 10^18 Bela.  They don't have that many Bela in their wallet, so the transaction will be rejected.  In order for the transaction to go through, they would have to be trying to send around 10^(-12) Bela or less in the first place.  But no reasonable person would send such a small amount of Bela, since the transaction fee alone is thousands of times more than the amount they are sending.  Thirdly, a warning message should successfully get the attention of users.  Fourthly, temporarily requiring "enter" or some bypass_warning to be passed in will prevent scripts from automatically executing the command and thus bring the change to any programmer's attention.

Thank you kindly for hearing me out.  I am happy to dicuss more.  Have a great day.
Matt

**Comment by cluracan** [comment]
The default technically isn't 1e-18, it's just the minimum unit. The rationale behind the current system is that tokens do not universally use 18 decimal places. Tether, for example, has only 6. So it was simpler to just fall back to minimum units.

This is a reasonable request, but I think the more robust answer would not be to default to 18, but instead to query the token contract before executing the transfer for the appropriate number of decimal places.

Regarding the option name, I think `-u` would make more sense, for `--units`, as a lot of people probably don't even really understand exponentiation either.

For migration, there already is a `--confirm` option, which should probably be made the default (requiring `--noconfirm` to bypass), and it would always echo the price as a decimal.

How's that?

**Comment by MareoRaft** [comment]
So if I understand you correctly, we would query the token contract first to know the number of decimal places.  For example, if using tether, and a user inputs `1`, they will send 1 token.  If they input `--units -6 <token> <to> 1`, they will send 0.000001 tokens.  If they input `--units -7 <token> <to> 1`, send-tokens will refuse to send and emit an error.  If they input `0.00000000001`, send-tokens will yet again emit an error.  I am happy with checking the decimal places ahead of time and refusing to send in these cases.

As for the option name, I like "units" better than "base", although I still prefer "exponent".  I like that someone can input `-e -6 <token> <to> 1` in the same way they might type `1e-6`.  How well the user understands may have more to do with the documentation.  If the documentation clearly explains that "this is the number of times the amount gets multiplied by 10" and includes a few examples, this will be very helpful.  But if you feel strongly, I think "units" is reasonable.  Either way, we should add a little extra documentation to elaborate.

I'm happy with the idea of making `--confirm` the default.  I think we should add an additional warning message in red to the confirmation message, which explains that a recent change was made to the library that affects the amount sent.

**Comment by cluracan** [comment]
`--units 6` would be `1e-6` or `0.000001`. 

What about just `-d, --decimals`? I think this option will probably fade into obscurity once auto decimals becomes the norm, so I probably wouldn't invest too much time into it.

**Comment by MareoRaft** [comment]
I'm okay with the units behaving as you say as long as it's documented.  If they input `--units -6` or any negative, I vote for emitting an error.

I'm happy with `decimals`.  It more closely means what it actually does, and I think users will understand it quickly.

**Comment by MareoRaft** [comment]
The only worry here is that if a user wants to send 100000000000 of a rather worthless token, they have to type out all the zeros.  The `decimals` option could potentially offer convenience in both directions if we're careful about our choice.

I'm not sure there is a benefit of making a positive number indicate that the amount gets smaller.  So I guess what I'm saying is I don't understand why you prefer negating the exponent.  This is opposite to the prevailing convention.  So I prefer `--decimals 6` to shift the decimal point to the right 6 times, while `--decimals -6` shifts the decimal point to the left 6 times.  I think this is natural.

As an aside, this could give my users extra convenience because my program will remember their preferences.  So if a user typically thinks about their currency in terms of "millions", they can set `decimals` to `6` and have the usage they prefer persist across sessions.

**Comment by cluracan** [comment]
It's just parity with the ERC20 standard, where `decimals` is the number of decimal places a whole number represents. So if someone reads a token contract on etherscan, they can plug the `decimals` value right into the CLI. 

Also, in crypto it's rare that someone would need to shift the decimal point to the right (only the absurdly wealthy or hyper-inflated tokens), but smaller units are regularly seen (like gwei/1e-9 for gas, or satoshis/1e-8 for bitcoin fees), which is why we have *many* names for small units but less so for large ones. 

Commander can handle negative input just fine, but it does look confusing to have a negative number as input, so the more common use case should be to keep the number positive.

**Comment by cluracan** [comment]
Applied with 9155a680ef7fbdce033163c9df94f0bdc33b1a3e

**Comment by MareoRaft** [comment]
Instead of making it all the way to the proceed prompt here:

    ~/Desktop/temp % send-tokens --decimals gibberish --key 0xe98a6804e4b6c832ed0ca876a6804e4b832ed0ca 0x2e98a6804e4b6c832ed0ca876a943abd3400b224 0x1e512fc62f01b6becf955b673a72085ca0e2ec2c 2
    Token: 0x2e98A6804E4b6c832ED0ca876a943abD3400b224 (18 decimal places)
    0x1E51Fa6e74ea58601Ac06bBE3A5eDF41a5bBbEde -> NaN -> 0x1E512fC62F01b6BecF955b673A72085ca0e2eC2c
    Proceed? [y/N]:

Can we capture a bad decimals input up-front and immediately error with "Bad value: illegal decimals amount" or similar?

**Comment by cluracan** [comment]
Sure. ea2c6f8

**Comment by MareoRaft** [comment]
Thanks!
