### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by MareoRaft** [cluracan/send-tokens#5]
How to reproduce:

    ~/Desktop/temp % send-tokens 0x2e98a6804e4b6c832ed0ca876a943abd3400b224 0x1e512fc62f01b6becf955b673a72085ca0e2ec2c 1
    Cannot read property 'toLowerCase' of undefined

I'm guessing the issue is that the private key is missing, and it's trying to make the private key lowercase.  If the private key is undefined, the error message should read "No private key inputted.  A private key is mandatory." or similar.

**Comment by MareoRaft** [comment]
I guess I'm striving for the most user-friendly error messages possible because I will be relaying such error messages to the users of my GUI.

**Comment by MareoRaft** [comment]
pull request coming soon...

**Comment by cluracan** [comment]
Fixed in ea2c6f8

Private key is not required. It will fall back to the node's wallet.

**Comment by MareoRaft** [comment]
okay
